language: android
dist: trusty
android:
  components:
    - android-30
    - build-tools-30.0.3
    - platform-tools-30.0.5
    - tools
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"
  
script:
  - chmod +x ./gradlew build connectedCheck
